name: two_value
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  cloud_functions: ^4.4.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.7
  image_cropper: ^3.0.1
  firebase_messaging: ^14.3.0
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.5.0
  firebase_crashlytics: ^3.0.17
  timeago: ^3.3.0
  google_sign_in: ^6.0.2
  flutter_launcher_icons: ^0.12.0
  animated_flip_counter: ^0.2.5
  intl: ^0.18.1
  flutter_native_splash: ^2.2.19
  animated_text_kit: ^4.2.2
  overlay_loader_with_app_icon: ^0.0.3
  in_app_update: ^4.0.1
  device_uuid: ^0.0.4
  flutter_local_notifications: ^13.0.0
  http: ^0.13.4
  number_selector: ^1.0.7
  flutter_advanced_segment: ^3.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_chat_bubble: ^2.0.2
  chips_choice: ^3.0.1
  path_provider: ^2.1.1
  easy_debounce: ^2.0.3
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  awesome_circular_chart: ^1.0.0
  linkwell: ^2.0.6
  carousel_slider: ^4.2.1
  fl_chart: ^0.64.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/personas/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/play_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "assets/images/play_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/images/play_logo.png"
    icon_size: 48 # min:48, max:256, default: 48

